
### Create a new report

POST http://localhost:3000/reports
content-type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "mileage": 1231,
  "lng": 0,
  "lat": 0,
  "price": 131312
}

### Update a new report

PATCH http://localhost:3000/reports/2
content-type: application/json

{
  "approved": false
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=toyota&model=crolla&lng=0&lat=0&mileage=200000&year=2030